import { existsSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));

/**
 * Phase 7.5: E2E では `apps/api` を `wrangler dev` で立ち上げるが、wrangler.toml
 * の `[vars]` は process.env では上書きできない。Turnstile bypass を成立させる
 * ため `.dev.vars` を保証する。`.dev.vars` は gitignore 済み — 既存ファイルは
 * 触らず、欠落している場合のみ E2E 用デフォルトを書き出す。
 */
export default async function globalSetup(): Promise<void> {
  const devVarsPath = path.resolve(__dirname, '../../api/.dev.vars');
  if (existsSync(devVarsPath)) return;

  const lines = [
    '# Auto-generated by apps/web/e2e/global-setup.ts for E2E.',
    '# Delete or replace freely; the setup only writes when this file is missing.',
    'BYPASS_TURNSTILE="true"',
    // Phase 7.6: 並列実行で 14+ rooms/min を作るため、production の RL (5/60s)
    // を bypass する。本番 wrangler.toml には書かない (bindings.ts の comment 参照)。
    'BYPASS_RATE_LIMIT="true"',
    'TURNSTILE_SECRET_KEY="1x0000000000000000000000000000000AA"',
    'ROOM_TOKEN_SECRET="e2e-test-token-secret-min-32-bytes-long-enough"',
    '',
  ];
  writeFileSync(devVarsPath, lines.join('\n'));
}
